### ISSUE TITLE
Cannot read property registerMetric of undefined

### ISSUE THREAD

**Issue by rrichardson** [mittwald/node-kubernetes#31]
I am using this in js from  npm `@mittwald/kubernetes` 
I get this when I try to instantiate any resource. 

```
> const { InClusterConfig, KubernetesRESTClient, KubernetesAPI } = require('@mittwald/kubernetes');
> const config = new InClusterConfig();
> const client = new KubernetesRESTClient(config);
> const api = new KubernetesAPI(client);
> api.apps().v1()
{ daemonSets: [Function: daemonSets],
  deployments: [Function: deployments],
  replicaSets: [Function: replicaSets],
  statefulSets: [Function: statefulSets] }
> api.apps().v1().deployments()
Thrown:
TypeError: Cannot read property 'registerMetric' of undefined
    at Counter.config.registers.forEach.registryInstance (/home/node/app/node_modules/prom-client/lib/counter.js:80:21)
    at Array.forEach (<anonymous>)
    at new Counter (/home/node/app/node_modules/prom-client/lib/counter.js:79:20)
    at new ResourceClient (/home/node/app/node_modules/@mittwald/kubernetes/resource.js:67:52)
    at new NamespacedResourceClient (/home/node/app/node_modules/@mittwald/kubernetes/resource.js:197:9)
    at KubernetesAPI.nc (/home/node/app/node_modules/@mittwald/kubernetes/api.js:12:16)
    at Object.deployments (/home/node/app/node_modules/@mittwald/kubernetes/api.js:52:41)
>
```

**Comment by rrichardson** [comment]
Based on some comments,  I assume that the construction of KubernetesAPI was meant to use a global Prometheus Client Registry,   since I'm not sure how to thread that in,  I just explicitly created a new one. 

A workaround is this: 
```
const promClient = require('prom-client');
const { Registry } = promClient;
const globalRegistry = new Registry();
... 
const api = new KubernetesAPI(client, globalRegistry); 
```

**Comment by martin-helmich** [comment]
Thanks for this report! The `registry` parameter should indeed be optional, as documented. #32 fixes this issue.

For future reference, the default global Prometheus registry can be obtained with

```js
const {register} = require("promClient");
```
